DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS debtors;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS incomes;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS access_keys;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS payment_method;
DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS goal_period;