// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/incomes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Devuelve una página de los ingresos del usuario autenticado, ordenados del más reciente al más antiguo. La respuesta viene envuelta en {\"data\": [...]}. Paginá con limit (entre 1 y 30, por defecto 30) y offset; el rango se acota con since y until en formato AAAA-MM-DD, y por categoría con category_id (el UUID de la categoría, no su nombre). Un parámetro mal formado responde 400. Los montos son enteros en pesos chilenos (CLP, sin decimales).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Incomes"
                ],
                "summary": "Listar ingresos del usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "cantidad maxima de ingresos a devolver (1-30, default 30)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ingresos a saltar, para pedir la pagina siguiente",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "fecha minima del rango (AAAA-MM-DD)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "fecha maxima del rango (AAAA-MM-DD)",
                        "name": "until",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "UUID de la categoria por la que filtrar",
                        "name": "category_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "pagina de ingresos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.Income"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "parametros de paginacion erroneos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Registra un nuevo ingreso asociado al usuario autenticado. La respuesta viene envuelta en {\"data\": ...} con el ingreso creado, incluyendo el id y las fechas que asigna la base. \"monto\" es un entero en pesos chilenos (CLP, sin decimales). \"category_id\" es opcional (la columna es nullable) y apunta a la tabla categories.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Incomes"
                ],
                "summary": "Registrar ingreso",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/incomes.IncomePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ingreso creado",
                        "schema": {
                            "$ref": "#/definitions/model.Income"
                        }
                    },
                    "400": {
                        "description": "payload del ingreso erroneo",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/app/incomes/{incomeID}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un ingreso por su ID, siempre que pertenezca al usuario autenticado. La respuesta viene envuelta en {\"data\": ...} con el mensaje de confirmación.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Incomes"
                ],
                "summary": "Eliminar ingreso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del ingreso",
                        "name": "incomeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ingreso eliminado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "incomeID invalido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ingreso no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/app/key": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Genera un código de acceso, lo guarda asociado al municipal autenticado (created_by) con un año de vencimiento y lo envía por correo al destinatario del payload. La respuesta viene envuelta en {\"data\": ...} con la llave creada; el código también viaja en el correo. Emitir es independiente de canjear: el emprendedor lo canjea después en POST /app/users/exchange/{code}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessKeys"
                ],
                "summary": "Emitir un código de acceso",
                "parameters": [
                    {
                        "description": "correo del destinatario",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accesskeys.EmailPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "código creado",
                        "schema": {
                            "$ref": "#/definitions/model.AccessKey"
                        }
                    },
                    "400": {
                        "description": "payload inválido o email mal formado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/app/key/AccessID/{keyID}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Vuelve a mandar por correo el código de una llave existente, sin crear una llave nueva ni mover su vencimiento: si el correo se perdió, el código sigue siendo el mismo. La respuesta viene envuelta en {\"data\": ...} con el mensaje de confirmación. Un keyID que no sea un UUID responde 400.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessKeys"
                ],
                "summary": "Reenviar el código de acceso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la llave de acceso",
                        "name": "keyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "correo del destinatario",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accesskeys.EmailPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "correo reenviado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "keyID inválido o payload inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error interno del servidor o llave inexistente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/app/key/revoke/{code}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Revoca una llave por su código, dejando registro de quién la revocó (revoked_by) y cuándo (revoked_at). Revocar es ortogonal a canjear y a vencer: deja la llave inútil aunque siga vigente. La respuesta viene envuelta en {\"data\": ...} con el mensaje de confirmación. Un código que no existe responde 404.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessKeys"
                ],
                "summary": "Revocar un código de acceso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "código de acceso a revocar",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "código revocado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "código vacío",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "código inexistente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/app/users": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un usuario de la base de datos",
                "tags": [
                    "Users"
                ],
                "summary": "Eliminar usuario",
                "responses": {
                    "200": {
                        "description": "usuario eliminado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "userID invalido",
                        "schema": {}
                    },
                    "404": {
                        "description": "usuario no encontrado",
                        "schema": {}
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza un usuario en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Actualizar usuario",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.UpdateUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "usuario actualizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "payload del usuario erroneo",
                        "schema": {}
                    },
                    "404": {
                        "description": "usuario no encontrado",
                        "schema": {}
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {}
                    }
                }
            }
        },
        "/app/users/exchange/{code}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Canjea un código de acceso y extiende el plan del usuario autenticado hasta el vencimiento de la llave. Un código ya canjeado, vencido o revocado se responde 400; uno inexistente, 404.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Canjear un código de acceso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "codigo de acceso",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "codigo canjeado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "codigo invalido, vencido, revocado o ya canjeado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "codigo inexistente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/app/users/municipal/{rut}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Busca un usuario por su rut",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Buscar usuario por rut",
                "parameters": [
                    {
                        "type": "string",
                        "description": "rut del usuario",
                        "name": "rut",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "usuario",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "rut invalido",
                        "schema": {}
                    },
                    "404": {
                        "description": "usuario no encontrado",
                        "schema": {}
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {}
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Registra un nuevo usuario y devuelve un token de autenticación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Registrar usuario",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token de autenticacion",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "payload erroneo o datos duplicados",
                        "schema": {}
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Inicia sesión con email y contraseña y devuelve un token de autenticación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginUserPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "token de autenticacion",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "credenciales invalidas",
                        "schema": {}
                    },
                    "500": {
                        "description": "error interno del servidor",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "accesskeys.EmailPayload": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "auth.CreateUserPayload": {
            "type": "object",
            "required": [
                "email",
                "nombre",
                "password",
                "rut"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 100
                },
                "nombre": {
                    "type": "string",
                    "maxLength": 100
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                },
                "rut": {
                    "type": "string",
                    "maxLength": 10
                }
            }
        },
        "auth.LoginUserPayload": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 100
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "incomes.IncomePayload": {
            "type": "object",
            "required": [
                "monto",
                "payment_method"
            ],
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string",
                    "maxLength": 100
                },
                "monto": {
                    "type": "integer"
                },
                "payment_method": {
                    "enum": [
                        "debito",
                        "credito",
                        "transferencia",
                        "efectivo"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.PaymentMethod"
                        }
                    ]
                }
            }
        },
        "model.AccessKey": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "redeemed_at": {
                    "type": "string"
                },
                "redeemed_by": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                },
                "revoked_by": {
                    "type": "string"
                }
            }
        },
        "model.Income": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                },
                "fecha": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "monto": {
                    "type": "integer"
                },
                "payment_method": {
                    "$ref": "#/definitions/model.PaymentMethod"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.PaymentMethod": {
            "type": "string",
            "enum": [
                "debito",
                "credito",
                "transferencia",
                "efectivo"
            ],
            "x-enum-varnames": [
                "PaymentMethodDebito",
                "PaymentMethodCredito",
                "PaymentMethodTransferencia",
                "PaymentMethodEfectivo"
            ]
        },
        "model.RUT": {
            "type": "object",
            "properties": {
                "cuerpo": {
                    "description": "Ej: 19234567",
                    "type": "integer"
                },
                "dv": {
                    "description": "Ej: \"K\" o \"4\"",
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "plan_expires_at": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.UserRole"
                },
                "rut": {
                    "$ref": "#/definitions/model.RUT"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.UserRole": {
            "type": "string",
            "enum": [
                "usuario",
                "municipal"
            ],
            "x-enum-varnames": [
                "UserRoleUsuario",
                "UserRoleMunicipal"
            ]
        },
        "users.UpdateUserPayload": {
            "type": "object",
            "properties": {
                "nombre": {
                    "type": "string",
                    "maxLength": 100
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Autorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Tally",
	Description:      "API para Tally, app financiera para emprendedores",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
